# Generated by Django 6.0.5 on 2026-06-01 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='ubdated_date',
            new_name='updated_date',
        ),
    ]
