# Generated by Django 6.0.5 on 2026-06-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog_posts/home-banner.jpg', upload_to='blog_posts'),
        ),
    ]
