# Generated by Django 6.0.5 on 2026-06-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=models.ImageField(default='blog_posts/images.png', upload_to='blog_posts'),
        ),
    ]
