# Generated by Django 6.0.5 on 2026-06-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_bio',
            field=models.CharField(default='Author Biography', max_length=155),
        ),
    ]
