# Generated by Django 6.0.5 on 2026-06-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='counted_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
